name: autoupdate
on:
  workflow_call
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ML
          ref: main
      - name: autoupdate
        uses: ./
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN_GITHUB }}"
          DRY_RUN: "false"
          PR_FILTER: "labelled"
          PR_LABELS: "autoupdate"
          MERGE_MSG: "Merged the changes to target branch from main"
          RETRY_COUNT: 100
          MERGE_CONFLICT_ACTION: "fail"
      - run: echo 'Merge conflicts found!'
        if: ${{ steps.autoupdate.outputs.conflicted }}

      - run: echo 'No merge conflicts'
        if: ${{ !steps.autoupdate.outputs.conflicted }}
